name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Debug - Check Flutter version
      run: flutter --version
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Create local.properties
      run: |
        echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
        echo "flutter.buildMode=release" >> android/local.properties
        echo "flutter.versionName=1.0.0" >> android/local.properties
        echo "flutter.versionCode=1" >> android/local.properties
    
    - name: Setup Gradle Wrapper
      run: |
        mkdir -p android/gradle/wrapper
        echo "distributionBase=GRADLE_USER_HOME" > android/gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> android/gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip" >> android/gradle/wrapper/gradle-wrapper.properties
        curl -L -o android/gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v7.6.1/gradle/wrapper/gradle-wrapper.jar
        chmod +x android/gradlew
    
    - name: Debug - Check Android project structure
      run: |
        echo "=== Android Project Structure ==="
        find android -type f -name "*.gradle" -o -name "*.properties" -o -name "*.xml" | head -20
        echo "=== Gradle Wrapper Files ==="
        ls -la android/gradle/wrapper/
        echo "=== Local Properties ==="
        cat android/local.properties
    
    - name: Debug - Check Flutter doctor
      run: flutter doctor -v
    
    - name: Debug - Check Android SDK
      run: |
        echo "=== Android SDK Location ==="
        echo $ANDROID_HOME
        echo "=== Android SDK Contents ==="
        ls -la $ANDROID_HOME/platforms/ || echo "No platforms directory"
        ls -la $ANDROID_HOME/build-tools/ || echo "No build-tools directory"
    
    - name: Build APK with verbose output
      run: |
        flutter build apk --release --verbose 2>&1 | tee build.log
        if [ $? -ne 0 ]; then
          echo "=== Build failed, showing last 50 lines of log ==="
          tail -50 build.log
          exit 1
        fi
    
    - name: Debug - Find APK files
      run: |
        echo "=== Searching for APK files ==="
        find . -name "*.apk" -type f
        echo "=== Build directory contents ==="
        ls -la build/ || echo "No build directory"
        ls -la build/app/ || echo "No build/app directory"
        ls -la build/app/outputs/ || echo "No build/app/outputs directory"
        ls -la build/app/outputs/flutter-apk/ || echo "No build/app/outputs/flutter-apk directory"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/apk/release/*.apk 